import type { PluginContext } from "@premium-cms/emdash/plugin";

export interface Settings {
	/** Master switch: webhook-triggered runs are ignored while off. */
	enabled: boolean;
	/** GitHub logins (lowercase) whose issues the agent may work on. */
	allowedUsers: string[];
	/** Secret the instance's runtime signs its callbacks with (generated by the plugin, never shown). */
	agentKey: string;
	/** Workers AI model id handed to the agent. */
	model: string;
	reasoning: "low" | "medium" | "high";
	/** How many CI runs a PR gets before the agent stops retrying (fix → build → test loops). */
	maxBuildAttempts: number;
	/** Squash-merge a PR into the default branch once every check passed. */
	autoMerge: boolean;
}

export const DEFAULTS: Settings = {
	enabled: true,
	allowedUsers: [],
	agentKey: "",
	model: "@cf/zai-org/glm-5.3-flash",
	reasoning: "high",
	maxBuildAttempts: 3,
	autoMerge: true,
};

const PREFIX = "settings:";

function clampAttempts(v: unknown): number {
	const n = Number(v);
	return Number.isFinite(n) && n >= 1 ? Math.min(Math.floor(n), 10) : DEFAULTS.maxBuildAttempts;
}

export function parseUsers(raw: unknown): string[] {
	if (Array.isArray(raw)) return raw.map(String).map(normalizeLogin).filter(Boolean);
	if (typeof raw !== "string") return [];
	return raw.split(/[\s,]+/).map(normalizeLogin).filter(Boolean);
}

export function normalizeLogin(login: string): string {
	return login.trim().replace(/^@/, "").toLowerCase();
}

export async function readSettings(ctx: PluginContext): Promise<Settings> {
	const map: Record<string, unknown> = {};
	for (const e of await ctx.kv.list(PREFIX)) map[e.key.slice(PREFIX.length)] = e.value;
	const reasoning = String(map.reasoning ?? "");
	return {
		enabled: typeof map.enabled === "boolean" ? map.enabled : DEFAULTS.enabled,
		allowedUsers: parseUsers(map.allowedUsers),
		agentKey: typeof map.agentKey === "string" ? map.agentKey : "",
		model: (typeof map.model === "string" && map.model.trim()) || DEFAULTS.model,
		reasoning: reasoning === "low" || reasoning === "medium" ? reasoning : "high",
		maxBuildAttempts: clampAttempts(map.maxBuildAttempts),
		autoMerge: typeof map.autoMerge === "boolean" ? map.autoMerge : DEFAULTS.autoMerge,
	};
}

export async function saveSettings(ctx: PluginContext, values: Record<string, unknown>): Promise<void> {
	if (typeof values.enabled === "boolean") await ctx.kv.set(`${PREFIX}enabled`, values.enabled);
	if (typeof values.allowedUsers === "string") {
		await ctx.kv.set(`${PREFIX}allowedUsers`, parseUsers(values.allowedUsers).join(", "));
	}
	// The callback secret is the plugin's own; a submitted value replaces it (rotation).
	if (typeof values.agentKey === "string" && values.agentKey.trim()) {
		await ctx.kv.set(`${PREFIX}agentKey`, values.agentKey.trim());
	}
	if (typeof values.model === "string") await ctx.kv.set(`${PREFIX}model`, values.model.trim() || DEFAULTS.model);
	if (values.reasoning === "low" || values.reasoning === "medium" || values.reasoning === "high") {
		await ctx.kv.set(`${PREFIX}reasoning`, values.reasoning);
	}
	if (values.maxBuildAttempts !== undefined) {
		await ctx.kv.set(`${PREFIX}maxBuildAttempts`, clampAttempts(values.maxBuildAttempts));
	}
	if (typeof values.autoMerge === "boolean") await ctx.kv.set(`${PREFIX}autoMerge`, values.autoMerge);
}

/** Master switch: with `enabled` off, webhooks and manual runs are ignored. */

/** The callback secret, generated on first use: the runtime signs its reports with it. */
export async function ensureAgentKey(ctx: PluginContext): Promise<string> {
	const existing = await ctx.kv.get<unknown>(`${PREFIX}agentKey`);
	if (typeof existing === "string" && existing.trim()) return existing;
	const key = `${crypto.randomUUID()}${crypto.randomUUID()}`.replace(/-/g, "");
	await ctx.kv.set(`${PREFIX}agentKey`, key);
	return key;
}
